image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/
    - client/node_modules/
    - server/node_modules/
install_dependencies:
  stage: build
  script:
    - npm install && cd client && npm install
  artifacts:
    paths:
      - node_modules
      - client/node_modules/
      - server/node_modules/
testing_testing:
  stage: test
  script: cd client && npm test && a